### ISSUE TITLE
Get referenceError after everytime rerendering 

### ISSUE THREAD

**Issue by dracarys55** [ubaimutl/react-portfolio#27]
![image](https://user-images.githubusercontent.com/20702380/188124044-14330522-e2a9-4641-9f2e-20d2c309e3bb.png)

This is what I get pretty much every time I change the code and trigger the screen to rerender.
How can I  fix it ?

And much thanks to the author who make this template, excellent work!!

**Comment by ubaimutl** [comment]
Did you use npm or yarn to install dependency ?

**Comment by dracarys55** [comment]
Yes, I tried both actually. But still...

**Comment by ubaimutl** [comment]
Fixed
